### ISSUE TITLE
production

### ISSUE THREAD

**Issue by Andrew22222** [yesnik/depot#1]
Привет такой вопрос , я развернул  проэкт на серевере  но  он не стартует выдает We're sorry, but something went wrong. и логи тоже чистые , поскажи может знаещь решение

**Comment by yesnik** [comment]
Привет, Андрей! Поскольку проект развернут на сервере, а не на локальном ПК, то, скорее всего, он работает в среде production. Страница "We're sorry, but something went wrong" сильно не помогает, т.к. скрывает от нас причину ошибки. Чтобы увидеть ошибку, можно пойти двумя путями:
1. Посмотреть логи в ```log/production.log```
2. Активировать показ ошибок вместо страницы "We're sorry, but something went wrong". Для этого нужно отредактировать файл ```config/environments/production.rb```:
```ruby
config.consider_all_requests_local = true
```
Напиши, пожалуйста, удалось ли тебе выявить ошибку?)

**Comment by Andrew22222** [comment]
Спасибо буду пробывать, как решу отпишусь

1 декабря 2015 г., 7:27 пользователь Nikita Nyatin <notifications@github.com

**Comment by Andrew22222** [comment]
Вообшем в config/environments/production.rb: нет вообше ни каких ошибок он
пустой и config.consider_all_requests_local = true тоже не чего не выводит
на экран . странно все это

1 декабря 2015 г., 18:33 пользователь Андрей Тону <andrei.richi@gmail.com>
написал:

**Comment by yesnik** [comment]
Андрей, вот этот файл: https://github.com/yesnik/depot/blob/master/config/environments/production.rb#L14 Это файл настроек для среды production.
В нем нужно изменить параметр на true. Тогда ошибки должны быть видны.

**Comment by Andrew22222** [comment]
Он  у  мне я стоит в значении true

2 декабря 2015 г., 7:39 пользователь Nikita Nyatin <notifications@github.com

**Comment by Andrew22222** [comment]
Привет , вобшем я развернул проект и все работает, но немного и наче  чем у
 тебя если надо  могу скинуть настроики

2 декабря 2015 г., 13:29 пользователь Андрей Тону <andrei.richi@gmail.com>
написал:

**Comment by yesnik** [comment]
Привет, Андрей! Здорово, что тебе удалось развернуть проект на удаленном сервере! Да, если можешь, покажи, какие настройки помогли тебе запустить проект)

**Comment by Andrew22222** [comment]
В config -> production.rb вставляем

          set :rails_env, ‘production’

          server '109.234.35.240', user: 'root', roles: %w{web app db},
primary: true
        В config -> deploy.rb вставляем

lock '3.4.0'

set :application, 'negroni_new'

set :repo_url, 'git@bitbucket.org:Virtuoz/negroni_new.git'


# Default branch is :master

# ask :branch, proc { `git rev-parse --abbrev-ref HEAD`.chomp }.call


# Default deploy_to directory is /var/www/my_app

set :deploy_to, "/home/root/#{fetch(:application)}"


# Default value for :scm is :git

# set :scm, :git


# Default value for :format is :pretty

# set :format, :pretty


# Default value for :log_level is :debug

# set :log_level, :debug


# Default value for :pty is false

# set :pty, true


# Default value for :linked_files is []

# set :linked_files, %w{config/database.yml}


# Default value for linked_dirs is []

# set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle
public/system}


# Default value for default_env is {}

# set :default_env, { path: "/opt/ruby/bin:$PATH" }


# Default value for keep_releases is 5

set :keep_releases, 2


set :rvm_type, :system

set :rvm_path, '/usr/local/rvm'


set :deploy_via, :remote_cache


set :unicorn_conf, "#{fetch(:deploy_to)}/current/config/unicorn.rb"

set :unicorn_pid, "#{fetch(:deploy_to)}/shared/tmp/pids/unicorn.pid"


set :delayed_job_args, '-n 4'


#set :linked_files, %w{config/application.yml}


set :linked_dirs, %w{log tmp/pids tmp/cache public/assets public/system}


namespace :deploy do


  desc 'Start Application'

  task :start do

    on roles(:all) do

      within release_path do

        execute :bundle, :exec, "unicorn -c #{fetch(:unicorn_conf)} -E
#{fetch(:rails_env)} -D"



      end

    end

  end


  desc 'Stop Application'

  task :stop do

    on roles(:all) do

      within release_path do

        execute "if [ -f #{fetch(:unicorn_pid)} ] && [ -e /proc/$(cat
#{fetch(:unicorn_pid)}) ]; then kill -QUIT `cat #{fetch(:unicorn_pid)}`; fi"



      end

    end

  end


  desc 'Restart application'

  task :restart do

    on roles(:all) do

      within release_path do

        execute "if [ -f #{fetch(:unicorn_pid)} ] && [ -e /proc/$(cat
#{fetch(:unicorn_pid)}) ]; then kill -QUIT `cat #{fetch(:unicorn_pid)}`; fi"

        execute :bundle, :exec, "unicorn -c #{fetch(:unicorn_conf)} -E
#{fetch(:rails_env)} -D"



      end

    end

  end


  after :publishing, :restart


  after :restart, :clear_cache do

    on roles(:web), in: :groups, limit: 3, wait: 10 do

      # Here we can do anything such as:

      # within release_path do

      #   execute :rake, 'cache:clear'

      # end

    end

  end

end



В unicorn.rb втавляем

# Set master PID location

deploy_to   = "/home/root/negroni_new"

rails_root  = "#{deploy_to}/current"

pid_file    = "#{deploy_to}/shared/tmp/pids/unicorn.pid"

socket_file = "#{deploy_to}/shared/unicorn.sock"

log_file    = "#{rails_root}/log/unicorn.log"

err_log     = "#{rails_root}/log/unicorn_error.log"

old_pid     = pid_file + '.oldbin'


timeout 60

worker_processes 2

listen socket_file, :backlog => 64

# listen 3030, :tcp_nopush => true

pid pid_file

stderr_path err_log

stdout_path log_file

stdout_path = "#{rails_root}/log/unicorn.log"

stdout_path = "#{rails_root}/log/unicorn_error.log"

stdout_path = "#{rails_root}/log/unicorn.stderr.log"


preload_app true


GC.copy_on_write_friendly = true if GC.respond_to?(:copy_on_write_friendly=)


before_exec do |server|

  ENV['BUNDLE_GEMFILE'] = "#{rails_root}/Gemfile"

end


before_fork do |server, worker|

  defined?(ActiveRecord::Base) and

  ActiveRecord::Base.connection.disconnect!


  if File.exists?(old_pid) && server.pid != old_pid

    begin

      Process.kill("QUIT", File.read(old_pid).to_i)

    rescue Errno::ENOENT, Errno::ESRCH

      # already killed

    end

  end

end


after_fork do |server, worker|

  defined?(ActiveRecord::Base) and

  ActiveRecord::Base.establish_connection

end



Вообшем както так :)

3 декабря 2015 г., 13:28 пользователь Nikita Nyatin <
notifications@github.com> написал:

**Comment by yesnik** [comment]
Адндрей, спасибо за предложенное решение
